<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-8UT20MC" failures="4" tests="6" name="Surefire test" time="23.426" errors="0" timestamp="2025-05-04T22:19:46 IST">
  <testcase classname="api.test.DDrivenTests" name="testDeleteRequest" time="0.0">
    <failure type="java.lang.RuntimeException" message="java.io.FileNotFoundException: C:\Users\VAISHNAV\eclipse-workspace\PetStoreAutomation\Userdata.xlsx (The system cannot find the file specified)">
      <![CDATA[java.lang.RuntimeException: java.io.FileNotFoundException: C:\Users\VAISHNAV\eclipse-workspace\PetStoreAutomation\Userdata.xlsx (The system cannot find the file specified)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)
Caused by: java.io.FileNotFoundException: C:\Users\VAISHNAV\eclipse-workspace\PetStoreAutomation\Userdata.xlsx (The system cannot find the file specified)
at java.base/java.io.FileInputStream.open0(Native Method)
at java.base/java.io.FileInputStream.open(FileInputStream.java:185)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:139)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:109)
at api.utilities.XLUtility.getRowCount(XLUtility.java:34)
at api.utilities.DataProviders.getUserNames(DataProviders.java:36)
... 30 more
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- testDeleteRequest -->
  <testcase classname="api.test.DDrivenTests" name="testPostRequest" time="0.0">
    <failure type="java.lang.RuntimeException" message="java.io.FileNotFoundException: C:\Users\VAISHNAV\eclipse-workspace\PetStoreAutomation\Userdata.xlsx (The system cannot find the file specified)">
      <![CDATA[java.lang.RuntimeException: java.io.FileNotFoundException: C:\Users\VAISHNAV\eclipse-workspace\PetStoreAutomation\Userdata.xlsx (The system cannot find the file specified)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)
Caused by: java.io.FileNotFoundException: C:\Users\VAISHNAV\eclipse-workspace\PetStoreAutomation\Userdata.xlsx (The system cannot find the file specified)
at java.base/java.io.FileInputStream.open0(Native Method)
at java.base/java.io.FileInputStream.open(FileInputStream.java:185)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:139)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:109)
at api.utilities.XLUtility.getRowCount(XLUtility.java:34)
at api.utilities.DataProviders.getAllData(DataProviders.java:17)
... 30 more
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- testPostRequest -->
  <testcase classname="api.test.UserTests" name="testPostUser" time="8.434"/>
  <testcase classname="api.test.UserTests" name="testGetByUserName" time="3.865"/>
  <testcase classname="api.test.UserTests" name="testUpdateByUserName" time="7.354">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.UserTests.testUpdateByUserName(UserTests.java:59)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- testUpdateByUserName -->
  <testcase classname="api.test.UserTests" name="testdeleteByUserName" time="3.083">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.UserTests.testdeleteByUserName(UserTests.java:67)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- testdeleteByUserName -->
</testsuite> <!-- Surefire test -->
